### ISSUE TITLE
jinjafmt adds trailing comma to macro args, breaking it

### ISSUE THREAD

**Issue by tconbeer** [tconbeer/sqlfmt#156]
**Describe the bug**
Jinja doesn't like trailing commas in macro arguments (?) but black inserts them when the args wrap to multiple lines

**To Reproduce**
```
{%- macro my_macro(
    arg_here,
    kwarg1=true,
    kwarg2="''",
    kwarg3="model",
    kwarg4="permanent",
    kwarg5=256
) -%}
```

**Expected behavior**
```
{%- macro my_macro(
    arg_here,
    kwarg1=true,
    kwarg2="''",
    kwarg3="model",
    kwarg4="permanent",
    kwarg5=256
) -%}
```

**Actual behavior**
```
{%- macro my_macro(
    arg_here,
    kwarg1=true,
    kwarg2="''",
    kwarg3="model",
    kwarg4="permanent",
    kwarg5=256,
) -%}
```
Unfortunately this doesn't compile because of the trailing comma after `256`

**Additional context**
What is the output of `sqlfmt --version`?
0.6.0

**Comment by mitchbregs** [comment]
Can't wait for `0.9.0`!!!

**Comment by tconbeer** [comment]
@mitchbregs released!
