### ISSUE TITLE
Improve formatting for chained boolean operators with complex expressions

### ISSUE THREAD

**Issue by tconbeer** [tconbeer/sqlfmt#189]
**Describe the bug**
Reported by @rainymood on [discourse](https://discourse.getdbt.com/t/introducing-sqlfmt-an-auto-formatter-for-dbt-sql/3687/3).

We're not very smart about building a hierarchy of chained boolean expressions; mixing simple expressions with complex expressions can produce unexpected and hard-to-read formatting.

**To Reproduce**

```sql
select *
from historic_answers ha
where 1=1
    and subject = 'Math' 
    and learningobjective = "Addition" 
    and dt_utc > date('2020-10-01') 
    and testschool = false
```

**Expected behavior**

```sql
select *
from historic_answers ha
where 
    1 = 1
    and subject = 'Math' 
    and learningobjective = "Addition" 
    and dt_utc > date('2020-10-01') 
    and testschool = false
```

**Actual behavior**

```sql
select *
from historic_answers ha
where
    1 = 1 and subject = 'Math' and learningobjective = "Addition" and dt_utc > date(
        '2020-10-01'
    ) and testschool = false
```

**Additional context**
What is the output of `sqlfmt --version`?
0.8.0

**Comment by tconbeer** [comment]
That's great to hear!

I'm not quite sure what a solution will look like just yet. The changes will be in `merger.py`, specifically in `_maybe_merge_segment()` and `_maybe_merge_operators()`

I think `_maybe_merge_operators()` needs some pretty major changes to scale to more edge cases.
1. I think ideally we would establish a hierarchy of sorts from the operators (we already sort of do this with "low priority" operators but that's much too simple). 
2. The other change is to that this method probably should be "all or nothing" for operators at a certain depth, so we don't create specifically the situation you encountered, where we merge the first 4 lines but not the last 1

Finally, right now, `_maybe_merge_operators()` runs first, and then `_maybe_merge_segment()` runs on the output, but I'm not convinced that is the right order of operations or overall approach.

Sorry I can't be more helpful here. `merger.py` is the hardest/most complicated logic of this whole app, and it's hard to intuit solutions. I'd really recommend test-driven development here, so you can try some things and see what works (and doesn't cause regressions).

**Comment by tconbeer** [comment]
Thinking about this a little more. 

If we change your query to:

```sql
select *
from historic_answers ha
where 1=1
    and subject = 'Math' 
    and learningobjective = "Addition" 
    and testschool = false
    and dt_utc > date('2020-10-01')  -- moved this to the end
```

sqlfmt does what you want.

The easiest/least destructive way to change this behavior is by changing `_line_continues_operator_sequence()` and the code that calls it to allow for blocks that are indented from the initial run of operators. After splitting, your code becomes

```sql
select *
from historic_answers ha
where 
    1=1
    and subject = 'Math' 
    and learningobjective = "Addition" 
    and dt_utc > date(
        '2020-10-01'
    ) 
    and testschool = false
```

We get the "bad" formatting because we merge the lines up to and including `and dt_utc > date(`, and don't consider the fact that `and testschool...` is in the same run of operators that should be merged together.

**Comment by tconbeer** [comment]
@Rainymood did you want to try to contribute to this? Otherwise I might be able to pick it up next week

**Comment by Rainymood** [comment]
No no go ahead! Would love to see this fixed :) 

Thanks for fixing the other issue so fast btw! Awesome!

**Comment by tconbeer** [comment]
@Rainymood This is merged to main now, but 0.10.0 may not be released for a while yet. If you want, you can install this patch with:

```sh
python -m pip install "shandy-sqlfmt[jinjafmt] @ git+https://github.com/tconbeer/sqlfmt.git@6efbf29510fc93b3d0d1bef0d8d6b2a310b9690a"
```

If you get that working, I'd love your feedback on the new style!

**Comment by Rainymood** [comment]
Yes! It works perfectly for me. I'm wondering though: is there a toggle to turn this behavior on/off or is this behavior now enabled by default? For the queries that I tested so far it looks really promising but I'll try to find more edge cases :)

**Comment by Rainymood** [comment]
There's also another reference in the comments around halfway this thread :). 

The changes seem great already, this change will be huge in support of my team adopting this :).
