### ISSUE TITLE
Add support for ClickHouse dialect

### ISSUE THREAD

**Issue by Shlomixg** [tconbeer/sqlfmt#193]
**Describe the bug**
sqlfmt doesn't support the ClickHouse dialect which is case sensitive.

**To Reproduce**
input code:
`
SELECT toString(1) AS Test_string, toDateTime64('2022-05-25', 3) AS Test_dateTime64, ifNull(null, 'TestNull') as testIf, JSONExtractString('{"abc": "hello"}', 'abc') as testJSON
`

**Expected behavior**
`select 
	toString(1) as Test_string, 
	toDateTime64('2022-05-25', 3) as Test_dateTime64, 
	ifNull(null, 'TestNull') as testIf, 
	JSONExtractString('{"abc": "hello"}', 'abc') as testJSON`

**Actual behavior**
`select
    tostring(1) as test_string,
    todatetime64('2022-05-25', 3) as test_datetime64,
    ifnull(NULL, 'TestNull') as testif,
    jsonextractstring('{"abc": "hello"}', 'abc') as testjson
`
this output is not a valid ClickHouse code

**Additional context**
What is the output of `sqlfmt --version`? 
`sqlfmt, version 0.9.0`

**Comment by tconbeer** [comment]
Thanks for the report, @Shlomixg !

I had no idea ClickHouse was case sensitive. (Why would they do that to us?!)

Should be easy enough to not lowercase the output, but...

Are SQL keywords (like select) also case sensitive, or is it just some/all function names?

I designed this with multiple dialects in mind, so it shouldn't be too bad to change the parsing logic to be case-sensitive. I'm just a little sad because we've gotten away with only one "polyglot" dialect so far.

**Comment by tconbeer** [comment]
Awesome, thank you for the extra info. That should make this pretty straightforward. We don't have to touch parsing and can still lowercase lots of tokens- we'll just leave identifiers (incl. function names) alone

**Comment by tconbeer** [comment]
Implementation notes (this is bigger than I thought, to get the `Dialect` or `Mode` into the `Node.capitalize()` method):

- Add Dialect as a property of Analyzer
- Create a `NodeManager` (`NodeBuilder`?) class with Dialect as a property
- instantiate a `NodeManager` where needed in `actions.py`
- move `Node.from_token()` to `NodeManager.create_node_from_token()`; also move `Node.capitalize()` and `Node.whitespace()`
- update `NodeManager.capitalize()` to check for the Clickhouse dialect
- update `Line.append_newline()` so it doesn't use `Node.from_token()`

**Comment by tconbeer** [comment]
@Shlomixg I'm cutting the release for 0.10.0 right now -- if you upgrade, you can run that version with `sqlfmt . --dialect clickhouse` and we won't lowercase so many things. Would love to get any more feedback from you!

**Comment by Shlomixg** [comment]
Bravo :)
I'll test it soon and leave feedback.
Thanks!
