### ISSUE TITLE
Recognise `using` as a keyword

### ISSUE THREAD

**Issue by nfcampos** [tconbeer/sqlfmt#218]
(sqlfmt is amazing, exactly what I was after.)

**Describe the bug**
It seems that currently `using` isn't recognised as a keyword, resulting in slightly odd formatting when used in a join clause see below. No space between `using` and the list of columns makes it look like a function call, which is confusing

**To Reproduce**
```
select a_column, b_column, c_column, d_column
from table_a
left outer join table_b using (id, something_else)
```

**Expected behavior**
```
select a_column, b_column, c_column, d_column
from table_a
left outer join table_b using (id, something_else)
```

**Actual behavior**
```
select a_column, b_column, c_column, d_column
from table_a
left outer join table_b using(id, something_else)
```

**Additional context**
What is the output of `sqlfmt --version`?
```sqlfmt, version 0.9.0```

**Comment by tconbeer** [comment]
For some reason I thought the canonical formatting of `using` was without a space, but checking the docs for a few dialects, I see that is wrong. This shouldn't be hard to fix. Thanks for the report!
