### ISSUE TITLE
SQL reserved words (such as SELECT, FROM etc.) and functions must not be formatted to lowercase

### ISSUE THREAD

**Issue by gmyrianthous** [tconbeer/sqlfmt#255]
**Describe the bug**
It was quite surprising to see that when a `.sql` file gets formatted, all reserved words in SQL syntax will be converted into lower case. This is considered as bad practise and should be among the first priorities of a SQL formatter tool. 

**To Reproduce**
Create a SQL file e.g.
```bash
SELECT 
  * 
FROM my_table;
```

and run `sqlfmt` over it. `SELECT` and `FROM` will be formatted into `select` and `from`.

**Expected behavior**
- The tool must not format SQL syntax into lowercase (and if possible, enforce uppercase for keywords if they are in lowercase format). 

**Additional context**
What is the output of `sqlfmt --version`? `sqlfmt, version 0.11.0`

**Comment by tconbeer** [comment]
I disagree. See [here](https://github.com/tconbeer/sqlfmt#why-lowercase) for the reasons and also [this comment](https://github.com/tconbeer/sqlfmt/discussions/229#discussioncomment-3311467) for more nuance
