### ISSUE TITLE
Tables containing `with timezone` produce unexpected results

### ISSUE THREAD

**Issue by frafra** [tconbeer/sqlfmt#265]
**Describe the bug**
It looks like `timestamp` messes up the formatting:

```diff
--- source_query
+++ formatted_query
@@ -65,12 +65,10 @@
     mass_mg int,
     attachment_method text,
     mount_method text,
-    startup timestamp with time zone,
-    deployment timestamp with time zone,
-    retrieval timestamp with time zone,
-    filename text,
-    notes text,
-    unique(survey, id)
+    startup timestamp
+    with time zone, deployment timestamp
+    with time zone, retrieval timestamp
+    with time zone, filename text, notes text, unique(survey, id)
 )
```

**To Reproduce**
Steps to reproduce the behavior. If this is a formatting issue, include the input code here.

**Expected behavior**
No change.

**Actual behavior**
See the diff.

**Additional context**
What is the output of `sqlfmt --version`?
`sqlfmt, version 0.11.1`

**Comment by tconbeer** [comment]
Thanks for the report!

Currently DDL like `create table` statements are not supported, but I'm currently planning out the first set of those features and this is helpful for those purposes.
