### ISSUE TITLE
Bug: whitespace added at the end of empty comment lines

### ISSUE THREAD

**Issue by eherde** [tconbeer/sqlfmt#319]
**Describe the bug**
`sqlfmt` adds whitespace at the end of empty comment lines. This is inconvenient especially because I have a pre-commit hook that removes whitespace errors.

**To Reproduce**
Run `sqlfmt --diff foo.sql`. Output below.

**Expected behavior**
The tool should output:
```
1 file passed formatting check.
```

**Actual behavior**
It currently outputs:
```
diff --git a/foo.sql b/foo.sql
index 60c8820694f9..8f350d458d59 100644
--- a/foo.sql
+++ b/foo.sql
@@ -1,7 +1,7 @@
 -- Here is an important comment. It is a comment about a very important and
 -- complicated piece of SQL. It is so complex that it is important that we
 -- can have multiple paragraphs of comments about it.
---
+--
 -- See, here is the very important next paragraph about my code. Any moment
 -- now, you will see the complex query once I am done with this paragraph.
 select 1
 ```
The whitespace is more visible in my terminal with git diff.
![Screen Shot 2022-11-16 at 17 37 12](https://user-images.githubusercontent.com/6392802/202332655-f5806eba-9526-41e2-8ca4-a47b4d2163de.png)

**Additional context**
```
sqlfmt, version 0.13.0
```

**Comment by tconbeer** [comment]
Thanks for the report, @eherde!

I agree this is a bug. We are standardizing white space in comments, need to make that conditional on there being content! Should be quite straightforward. I'll squeeze this into v0.14 (next few weeks).

**Comment by tconbeer** [comment]
@eherde This patch has been merged to main. Thanks again for the report!
