### ISSUE TITLE
Bug when formatting float literals in BigQuery

### ISSUE THREAD

**Issue by liaopeiyuan** [tconbeer/sqlfmt#321]
**Describe the bug**
`sqlfmt` adds unnecessary spaces for float literals in E notation in BigQuery

**To Reproduce**
`1e-9`

**Expected behavior**
`1e-9`

**Actual behavior**
`1 e -9`

**Additional context**
We are using the sqlfmt embedded in dbt develop. The UI on `https://sqlfmt.com/` produces the same result.

**Comment by tconbeer** [comment]
Thanks for the report, @liaopeiyuan . I knew, and then forgot, that number literals could use scientific notation. This is true in postgres too. This is definitely a bug; I'll get this fixed asap.

We just need to change the `number` Rule to add a pattern that will match something like `1e-9` or `-55.55e10`. Decimals after the `e` are not supported (at least on pg).

https://github.com/tconbeer/sqlfmt/blob/f349abe38544b530f06aab64e3862a57e4d39a8e/src/sqlfmt/rules/core.py#L70-L76

**Comment by tconbeer** [comment]
@liaopeiyuan This patch has been merged to main. Thanks again for the report!
