### ISSUE TITLE
Match against files *.sql suffix

### ISSUE THREAD

**Issue by ysmilda** [tconbeer/sqlfmt#354]
**Describe the bug**
Currently the CLI matches against files ending on the `.sql` and `.sql.jinja` suffix. In our product we have various files that are suffixed `.{something}.sql`, these can currently not be formatted by `fmtsql`.

**To Reproduce**
Rename file to have a suffix of `.{something}.sql`.

**Expected behavior**
It would be nice if the cli could check against `*.sql` as a suffix to be able to format these kind of files.

**Additional context**
sqlfmt, version 0.14.3

**Comment by tconbeer** [comment]
I'm ok with this. Also looks like one of our benchmark projects (http archive) has a bunch of files with extra dots in the filename, like `19_01.type_of_content_encoding.sql`.
