### ISSUE TITLE
Incorrect formatting of bun placeholders (e.g. `?1`)

### ISSUE THREAD

**Issue by ysmilda** [tconbeer/sqlfmt#356]
**Describe the bug**
In our sql files we make use of placeholders (`?0`) so that these can be replaced dynamically when read by [bun](https://bun.uptrace.dev/guide/placeholders.html). When ran through `sqlfmt` it adds a space between the `?` and the `0`. The following statement `"time" = ?0` becomes `"time" = ? 0` which makes it invalid.

This is not a feature of standard SQL but I would expect the formatter to leave these statements as is. My assumption is that the `?` is read as a statement of it's own, but I can't locate the source of it.

**To Reproduce**
See example above

**Expected behavior**
I would expect no formatting to happen between these characters.

**Additional context**
sqlfmt, version 0.14.3

**Comment by tconbeer** [comment]
Similar to psycopg placeholders #198 and pg variables/placeholders https://github.com/tconbeer/sqlfmt/pull/296/commits/a5d7dd0c4f53084ad3dfeaa493248621dfaa1669

Looks like bun's syntax is `r"\?\d*"`, including the bare `?`, which collides with the use of `?` as an operator in some dialects (we're parsing `?` as an operator now). e.g., postgres: `jsonb ? text → boolean`

But I think we can easily support `r"\?\d+"` in the `other_identifiers` rule without any bad side-effects. Change would be here:
https://github.com/tconbeer/sqlfmt/blob/3a2b998a24b8c3f6d3d0d33c6204bc7bed1b503f/src/sqlfmt/rules/core.py#L134-L144

**Comment by ysmilda** [comment]
That indeed did the trick, see #358
