### ISSUE TITLE
Adding space to comment breaks bun migrations

### ISSUE THREAD

**Issue by ysmilda** [tconbeer/sqlfmt#369]
In a [Bun](https://bun.uptrace.dev/guide/migrations.html#go-based-migrations) migrations comments are used to split up multiple statements. These are of the format `--bun:split` (the docs use `migration` which is [wrong](https://github.com/uptrace/bun/blob/635592d332ba8d5d3aac981686646ba306cabee2/migrate/migration.go#L61)).

As bun scans for `--bun` specifically adding a space in between will break functionality. It shouldn't be to add this edge case but the question becomes till which point you want to support every syntax out there.

**Comment by tconbeer** [comment]
yeah, I don't really want to support a specific comment marker. One option would be a flag to disable any processing of comments (we add whitespace and wrap long comments), but I don't like being able to configure style. (admittedly, black does this for strings). 

For now, can you just fix it with `sed`?

```bash
sqlfmt . && find . -type f -name "*.up.sql" | xargs sed -i "s/-- bun:split/--bun:split/g"
```

**Comment by ysmilda** [comment]
I agree with your reasoning and will fix this in an additional step. Let's keep sqlfmt clean of these caveats.
