### ISSUE TITLE
Space inserted into column name causes syntax error

### ISSUE THREAD

**Issue by cmcnicoll** [tconbeer/sqlfmt#378]
**Describe the bug**
Not sure if this is an issue or if the column naming convention is not recommended.

**To Reproduce**
Input:
```
{{ entity }}1_key,
{{ entity }}1_name,
{{ entity }}2_key,
{{ entity }}2_name,
{{ entity }}3_key,
{{ entity }}3_name,
```

**Expected behavior**
Expected formatting (no change):
```
{{ entity }}1_key,
{{ entity }}1_name,
{{ entity }}2_key,
{{ entity }}2_name,
{{ entity }}3_key,
{{ entity }}3_name,
```

**Actual behavior**
Output:
```
{{ entity }}1 _key,
{{ entity }}1 _name,
{{ entity }}2 _key,
{{ entity }}2 _name,
{{ entity }}3 _key,
{{ entity }}3 _name,
```

**Additional context**
What is the output of `sqlfmt --version`?
`sqlfmt, version 0.16.0`

**Comment by tconbeer** [comment]
Interesting. Thanks for the report. I know why this is happening -- not sure what the right solution is. Basically, in normal circumstances names can't start with a number, so we're parsing a the number separately. 

As a workaround, you can concatenate the number inside the jinja:

`{{ entity ~ "1" }}_foo` should work just fine.

**Comment by cmcnicoll** [comment]
Concatenating the number works fine for me. It also makes the code easier to read. Thanks!
