### ISSUE TITLE
Failed formatting with CTE and CASE statement

### ISSUE THREAD

**Issue by AndrewLaneAtPowerSchool** [tconbeer/sqlfmt#395]
**Describe the bug**
Formatting failure on code that I **think** should succeed

**To Reproduce**
Try to format:
```
CREATE OR REPLACE VIEW someview AS
WITH some_cte AS (
    SELECT
        CASE
            WHEN foo = bar THEN 1
            ELSE 0
        END AS biz
    FROM
    BAT
)
select * from some_cte
```

**Expected behavior**
Expecting formatting to succeed without an error.

**Actual behavior**
```
sqlfmt encountered an error: Closing bracket ')' found at 167 does not match last opened bracket 'CASE' found at 65.
```

**Additional context**
What is the output of `sqlfmt --version`?
```0.14.2``` but I was able to reproduce it on the https://sqlfmt.com/ sandbox as well.

**Comment by tconbeer** [comment]
We don't format CTAS statements yet, partially because of the complexity with parsing the stuff after AS... using a different rule set. See the DDL tracking issue for more info. 

I think if you wrap the whole WITH...SELECT statement on in parens, it should at least not error. Eg this should not error:

```sql
Create table foo as (
 With bar as (
  ...
 )
 Select * from bar
)
```

**Comment by AndrewLaneAtPowerSchool** [comment]
> We don't format CTAS statements yet, partially because of the complexity with parsing the stuff after AS... using a different rule set. See the DDL tracking issue for more info. #301 #262
> 
> I think if you wrap the whole WITH...SELECT statement in parens, it should at least not error. Eg this should not error:
> 
> ```sql
> Create table foo as (
>  With bar as (
>   ...
>  )
>  Select * from bar
> )
> ```

Thanks for the quick response.  I tried this but still couldn't get it to not error.
```
CREATE OR REPLACE VIEW someview AS (
WITH some_cte AS (SELECT CASE WHEN foo = bar THEN 1 ELSE 0 END AS biz FROM BAT)
select * from some_cte
)
```
