### ISSUE TITLE
BigQuery STRUCT function

### ISSUE THREAD

**Issue by daniel-bartley** [tconbeer/sqlfmt#424]
**Describe the bug**
sqlfmt does not know about the STRUCT function in BigQuery. 
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#struct_type

Without the jargon, STRUCT groups columns into a table embedded into the result set.

**To Reproduce**
```
SELECT 
   "abc" as my_col,
   STRUCT(
       123 as my_integer,
       "abc" as my_str,
       "2024-01-01" as my_date,
       True as my_bool
   ) as my_struct
 FROM my_table
 
 ```

**Expected behavior**
I would prefer the formatter formatted the code as per the original string where:
- struct creates an indented section something like a subquery
- each column in the struct is formatted as a distinct column

**Actual behavior**
 ```
 select
    "abc" as my_col,
    struct(
        123 as my_integer, "abc" as my_str, "2024-01-01" as my_date, true as my_bool
    ) as my_struct
from my_table
```

**Additional context**
What is the output of `sqlfmt --version`?

$ sqlfmt --version
sqlfmt, version 0.17.0

**Comment by tconbeer** [comment]
This is merging into a single line because it fits, which is generally the rule. You may be interested in #discussion

**Comment by daniel-bartley** [comment]
I acknowledge this is a bad example. Lemme make another one
