### ISSUE TITLE
Multiple select statements occur in the same line.

### ISSUE THREAD

**Issue by seanpwlms** [tconbeer/sqlfmt#441]
**Describe the bug**
Short queries with a CTE format to have multiple select statements on one line, which is harder to read

**To Reproduce**
```
with cte as (select * from table1) 
select col1 from cte
```

**Expected behavior**

```
with cte as (select * from table1) 
select col1 from cte
```

**Actual behavior**
`with cte as (select * from table1) select col1 from cte`

**Additional context**
This was formatted on the project website

**Comment by tconbeer** [comment]
See https://github.com/tconbeer/sqlfmt/discussions/334

**Comment by seanpwlms** [comment]
That makes sense to me the the context of "segments." To me though, I would expect a `select` statement that isn't nested to have a new line.
