### ISSUE TITLE
`exclude` option does not follow symlinks when generating `exclude_set` for relative paths in Python <3.13

### ISSUE THREAD

**Issue by jeancochrane** [tconbeer/sqlfmt#457]
**Describe the bug**

Given the following directory structure:

```
testdir/
    subdir/
        include_me.sql
    venv/
        symlink/ => ../../sourcedir/
sourcedir/
    exclude_me.sql
```

If we try to run `sqlfmt testdir --exclude "testdir/venv/**/*"`, `testdir/venv/symlink/exclude_me.sql` will not be excluded, due to a [known bug in Python <3.13](https://github.com/python/cpython/issues/77609) that prevents `pathlib.Path.glob()` from following symlinks in this code block:

https://github.com/tconbeer/sqlfmt/blob/abf97631cb753a77d6029f40286e6d5fb80cee5c/src/sqlfmt/api.py#L111-L114 

This is particularly a problem for directories containing Python virtual environments, where [`lib64/` is often a symlink to `lib/`](https://stackoverflow.com/a/11370995) and can contain third-party packages that should be excluded by `sqlfmt`. 

**To Reproduce**

Create the above directory structure:

```
mkdir -p testdir/subdir/
touch testdir/subdir/include_me.sql
mkdir sourcedir
touch sourcedir/exclude_me.sql
mkdir testdir/venv
ln -s "`pwd`/sourcedir" testdir/venv/symlink
```

Run sqlfmt and try to exclude `testdir/venv/**/*`:

```
$ sqlfmt testdir/ -v --check --exclude "testdir/venv/**/*"
```

**Expected behavior**

With the above directory structure, sqlfmt should follow the symlink and exclude `exclude_me.sql`:

```
$ sqlfmt testdir/ -v --check --exclude "testdir/venv/**/*"
1 file passed formatting check.
testdir/subdir/include_me.sql passed formatting check.
```

**Actual behavior**

sqlfmt includes `exclude_me.sql`:

```
$ sqlfmt testdir/ -v --check --exclude "testdir/venv/**/*"
2 files passed formatting check.
testdir/subdir/include_me.sql passed formatting check.
testdir/venv/symlink/exclude_me.sql passed formatting check.
```

**Additional context**

I'm not totally sure what the right way to handle this is, given that the underlying `Path.glob()` bug will be fixed in the upcoming Python 3.13 release. It seems like the choice that would support a wider range of versions would be to replace the `Path.glob()` call with a relative `glob.glob()` call, [which seems to be a common workaround](https://stackoverflow.com/a/57594612), but I don't know how high priority it is to support this behavior. If you agree with switching to `glob.glob()`, I'd be happy to put up a patch!

**Comment by tconbeer** [comment]
Didn't realize that; 3.13 seems pretty far away, so I'd love a patch and a test if you could! Feel free to reach out if you need any help.

Similar but probably not related to #440 

I'm fine if you want to leave Windows symlinks for another issue.

**Comment by jeancochrane** [comment]
Thanks @tconbeer, I'll aim to make some time for a patch this week!

**Comment by jeancochrane** [comment]
Thanks for the quick turnaround @tconbeer, my team really appreciates it!

**Comment by tconbeer** [comment]
You made it very easy for me!
