### ISSUE TITLE
Snowflake JSON fields case sensitive keyword are wrongly lower-cased

### ISSUE THREAD

**Issue by adrien-brunelat-sb** [tconbeer/sqlfmt#475]
**Describe the bug**
In snowflake you can directly access JSON fields with the syntax: `my_json_column:Field:SubField::string`
The JSON fields are case sensitive and won't return anything if the word is lowercased by the formatter resulting in null values.

**To Reproduce**
`select MY_JSON:Field::String as Field from json_table;`

**Expected behavior**
`as Field`, `MY_JSON` and `::String` should be lowercased but `:Field` shouldn't.
expected result: `select my_json:Field::string as field from json_table;`

**Actual behavior**
Everything is put to lowercase, breaking the :Field reference to JSON data.
actual result: `select my_json:field::string as field from json_table;`

**Additional context**
Latest snowflake / sqlfmt version

**Comment by tconbeer** [comment]
This duplicates #269. Please see the help wanted comment.

**Comment by adrien-brunelat-sb** [comment]
oops, sorry about that. I didn't search for open issues before posting.
