### ISSUE TITLE
Formatting of ClickHouse aggregate function `any` results in extra whitespace and poor formatting

### ISSUE THREAD

**Issue by damirbk** [tconbeer/sqlfmt#483]
**Describe the bug**
sqlfmt doesn't seem to understand that the `any` function is an aggregate function and not the typical SQL ANY operator. See examples below.

**To Reproduce**
File `example1.sql`:
```sql
select any(number) as any_number from (select number from system.numbers limit 10)
```

Also, file `example2.sql`:
```sql
select max(number) as max_number, min(number) as min_number, any(number) as any_number, avg(number) as avg_number from (select number from system.numbers limit 10)
```

**Expected behavior**
For `example1.sql`:
```sql
select any(number) as any_number from (select number from system.numbers limit 10)
```
(no change)

For `example2.sql`:
```sql
select
    max(number) as max_number,
    min(number) as min_number,
    any(number) as any_number,
    avg(number) as avg_number
from (select number from system.numbers limit 10)
```

**Actual behavior**
After running `sqlfmt example1.sql --dialect clickhouse --line-length 88`:
```sql
select any (number) as any_number from (select number from system.numbers limit 10)
```
Extra whitespace is added incorrectly.

After running `sqlfmt example2.sql --dialect clickhouse --line-length 88`:
```sql
select
    max(number) as max_number,
    min(number) as min_number, any (number) as any_number,
    avg(number) as avg_number
from (select number from system.numbers limit 10)
```

**Additional context**
What is the output of `sqlfmt --version`?

`sqlfmt, version 0.19.2`

**Comment by tconbeer** [comment]
Thanks for the report!

Does the formatted code execute on clickhouse or does it complain about the space?

**Comment by damirbk** [comment]
Thanks for all the work you do! It actually works fine in ClickHouse with the spaces; it's just the formatting that becomes strange.

**Comment by tconbeer** [comment]
Cool, thanks, snowflake is the same way.
