### ISSUE TITLE
Not automatically formatting when running from CLI ? 

### ISSUE THREAD

**Issue by wtfzambo** [tconbeer/sqlfmt#497]
**Describe the bug**
I run `sqlfmt myfile.sql` or `sqlfmt .` from the CLI, and even if it can detect that a file needs formatting, it doesn't automatically apply it. Works ok when running in tandem with dbt-power-user and set as format when "format on save" is on. 

If I run:
```sh
cat myfile.sql | sqlfmt -
```
the output is:
```sh
1 file failed formatting check.
0 files passed formatting check.
- failed formatting check.
```

However, `--diff` works fine and properly shows the rows it would change.

**To Reproduce**
I'm in a pretty standard bread and butter dbt project, running in a devcontainer:
- Debian GNU/Linux 12 (bookworm)
- Python 3.11
- sqlfmt v0.20.0
- `pyproject.toml`
```toml
[tool.sqlfmt]
exclude = ["./.venv/**", "./dbt/target/**/*", "./dbt/dbt_packages/**/*"]
check = true
line_length = 88
```

**Expected behavior**
sqlfmt actually formats files in place when called from the CLI.

**Actual behavior**
sqlfmt detects files that need formatting, but doesn't change them.

**Additional context**
What is the output of `sqlfmt --version`?

![image](https://github.com/tconbeer/sqlfmt/assets/47462792/e4482226-535a-4ae4-81b1-ad7be83a6b42)

**Comment by tconbeer** [comment]
The check=true config in your file prevents changes from being written to the file. Remove that config for the behavior you want.

**Comment by wtfzambo** [comment]
> The check=true config in your file prevents changes from being written to the file. Remove that config for the behavior you want.

AH there you go, I knew I was being stupid somewhere. Thanks! Sorry for opening a stupid issue.
