### ISSUE TITLE
Strange formatting for Athena SQL array/map types

### ISSUE THREAD

**Issue by benjamin-awd** [tconbeer/sqlfmt#500]
**Describe the bug**
Athena has array and map [datatypes](https://docs.aws.amazon.com/athena/latest/ug/data-types.html), that use `<` and `>` characters. Running sqlfmt on queries that use these types produce unexpected behaviour.

**Expected behavior**
```sql
select cast(json_parse(foo) as array<map<varchar,varchar>>) from dwh.table
```

**Actual behavior**
Strange spacing in between < and > separators
```sql
select cast(json_parse(foo) as array<map < varchar, varchar> >) from dwh.table
```

**Additional context**
What is the output of `sqlfmt --version`?
```
sqlfmt, version 0.20.0
```
Note: non-breaking, but not ideal

**Comment by tconbeer** [comment]
We support similar syntax for structs amd arrays in BQ. I think we may just have to add the "map" keyword into that lever.

**Comment by benjamin-awd** [comment]
Raised a PR: https://github.com/tconbeer/sqlfmt/issues/500

**Comment by benjamin-awd** [comment]
So apparently sqlfluff lints `map<...>` statements, and actually expects something like this:
`select cast(json_parse(foo) as array<map <varchar, varchar>>) from dwh.table`

The specific sqfluff rule is:
```
L:  57 | P:  57 | LT01 | Expected single whitespace between 'map' keyword and                    
                       | start angle bracket '<'. [layout.spacing]
```

Not sure if the best solution here is to simply ignore the `layout.spacing` rule

**Comment by tconbeer** [comment]
Yeah that makes no sense to have a space after map but not array. I'd ignore that rule.
