### ISSUE TITLE
formatting does not work in queries defined as variables

### ISSUE THREAD

**Issue by mgsnuno** [tconbeer/sqlfmt#535]
**Describe the bug**
formatting does not work in [queries defined as variables](https://docs.getdbt.com/reference/dbt-jinja-functions/run_query)

**To Reproduce**
format the following:
```sql
{% set payment_methods_query %}
select payment_method, payment_amount, payment_currency, payment_date from app_data.payments where payment_date > '2023-03-03' 
{% endset %}
```

**Expected behavior**
query should be formatted:
```sql
{% set payment_methods_query %}
select payment_method, payment_amount, payment_currency, payment_date
from app_data.payments
where payment_date > '2023-03-03'
{% endset %}
```
**Actual behavior**
nothing is formatted:
```sql
{% set payment_methods_query %}
select payment_method, payment_amount, payment_currency, payment_date from app_data.payments where payment_date > '2023-03-03' 
{% endset %}
```

**Additional context**
sqlfmt, version 0.21.0

**Comment by tconbeer** [comment]
This is expected behavior; `{% set %}` blocks contain arbitrary data -- we don't have any way to know that those blocks contain SQL that can be safely formatted.

**Comment by mgsnuno** [comment]
ok, thank you, would it be possible to tag the blocks we want to be formatted?

**Comment by tconbeer** [comment]
Feel free to propose a syntax for that as a new discussion; I'm going  to close this issue for now.
