### ISSUE TITLE
--exclude option doesn't work on Windows

### ISSUE THREAD

**Issue by cubeprodata** [tconbeer/sqlfmt#540]
**Describe the bug**
--exclude option doesn't work for nested files - we noticed it only on Windows(works on Mac and Linux)

In the example below, file directly under excluded folder is ignored whilst file in a subfolder is not. 

![image](https://github.com/tconbeer/sqlfmt/assets/154617114/1607874a-54be-491f-8871-b65c3101576c)

**To Reproduce**
Create folder with subfolder and file in it.

Run `sqlfmt . --exclude "./folder/**/*"` 

**Expected behavior**
All files in excluded folder should be ignored

**Actual behavior**
Files in excluded folder are formatted

**Additional context**
What is the output of `sqlfmt --version`?

see on screenshot

What is the output of `pip list` (or `pipx list` if you installed using pipx)?

see on screenshot

**Comment by tconbeer** [comment]
Agreed. Duplicates #440
