### ISSUE TITLE
Case-sentitive identifiers within object navigation expressions are lowercased

### ISSUE THREAD

**Issue by albertsgrc** [tconbeer/sqlfmt#561]
**Describe the bug**
sqlfmt changes case of identifiers within object navigation expressions (syntactic sugar for snowflake's [get_path](https://docs.snowflake.com/en/sql-reference/functions/get_path))

**To Reproduce**
```sql
select {'key':2, 'Key':3}:Key
```

**Expected behavior**
SQL remains unchanged. Lowercasing `:Key` will cause the query to return 2 instead of 3

**Actual behavior**
```sql
select {'key':2, 'Key':3}:key
```

**Additional context**
Reproducible from https://sqlfmt.com/

Syntax: Snowflake

**Comment by albertsgrc** [comment]
There is a workaround, wrapping the identifier within quotes:

```sql
select {'key':2, 'Key':3}:"Key"
```

**Comment by tconbeer** [comment]
duplicates #269
