### ISSUE TITLE
sqlfmt adds an extra space to PostgreSQL double tilda operators (`LIKE` alias) 

### ISSUE THREAD

**Issue by tuckerrc** [tconbeer/sqlfmt#576]
**Describe the bug**

PostgreSQL has a few aliases for the `LIKE`  keyword ([9.7.1. LIKE](https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-LIKE)). sqlfmt adds a space between the `~~` operator, breaking the query.

Other operators specific to PostgreSQL (from the docs)

> The operator `~~` is equivalent to `LIKE`, and `~~*` corresponds to `ILIKE`. There are also `!~~` and `!~~*` operators that represent `NOT LIKE` and `NOT ILIKE`, respectively. All of these operators are PostgreSQL-specific.

**To Reproduce**
Steps to reproduce the behavior. If this is a formatting issue, include the input code here.

Input
```sql
with test as (select 'test' as test) select * from test where test ~~ 'test'
```
sqlfmt output
```sql
with test as (select 'test' as test) select * from test where test ~ ~ 'test'
```

**Expected behavior**

No spaces are added to the `~~` operator

**Additional context**
What is the output of `sqlfmt --version`?

```
$ sqlfmt --version
sqlfmt, version 0.21.2
```

**Comment by tconbeer** [comment]
Had no idea that was a thing. Thanks for the report!

**Comment by tuckerrc** [comment]
Thank you for the quick turnaround! I discovered it yesterday when sqlfmt broke a query in a large project. Now I don't need to change that query!
