### ISSUE TITLE
PostgreSQL formatting of extensions is broken

### ISSUE THREAD

**Issue by oleorhagen** [tconbeer/sqlfmt#591]
**Describe the bug**

Using the single line example:

```sql
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
```
Run `sqlfmt` on it, and get:

```sql
CREATE EXTENSION IF NOT EXISTS uuid-ossp;
```
Run `sqlfmt` again, and it now errors.

**To Reproduce**

More succintly:

```terminal
cat 001_init.sql
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
```

```terminal
cat 001_init.sql | sqlfmt 
CREATE EXTENSION IF NOT EXISTS uuid-ossp;
```

```terminal
cat 001_init.sql | sqlfmt | sqlfmt
at or near "-": syntax error
```

**Expected behavior**

I expect the formatting to be idempotent, and not format it to something which the tool itself thinks is invalid.

**Actual behavior**
See above.

**Additional context**
```
sqlfmt --version
sqlfmt 0.5.0
```

Tool is installed as an arch-linux package.

**Comment by tconbeer** [comment]
You're using the wrong package. You install this one with

pip install shandy-sqlfmt

**Comment by oleorhagen** [comment]
> You're using the wrong package. You install this one with
> 
> pip install shandy-sqlfmt

Oh my, I apologize. Old outdated arch linux package tripped me up. :pray:
