### ISSUE TITLE
Request: Implement in compiled language

### ISSUE THREAD

**Issue by mcandre** [tconbeer/sqlfmt#592]
Hi,

I'm excited to normalize the format of my SQL code!

Can we please implement sqlfmt in a compiled language like Go?

That way, users aren't forced to install or maintain any programming languages in order to run sqlfmt.

**Comment by tconbeer** [comment]
I won't be the one to port this to another language. If you want to, please do.

You can run sqlfmt in a docker container very easily if you don't want to install python. See [here](https://docs.sqlfmt.com/getting-started/using-container) for the docs.
