### ISSUE TITLE
return in finally swallows exceptions

### ISSUE THREAD

**Issue by iritkatriel** [tconbeer/sqlfmt#638]
In
https://github.com/tconbeer/sqlfmt/blob/e9205a9acaaa8726b6e35bb7e5a2244cbaff5860/src/sqlfmt/jinjafmt.py#L76 
and
https://github.com/tconbeer/sqlfmt/blob/e9205a9acaaa8726b6e35bb7e5a2244cbaff5860/src/sqlfmt/jinjafmt.py#L81
there is a `return` statement in a `finally` block, which would swallow any in-flight exception.

This means that if any unhandled exceptions (including a `BaseException` such as `KeyboardInterrupt`) is raised from the `try` body, or any exception is raised from an `except:` clause, it will not propagate on as expected.

See also https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions.

**Comment by tconbeer** [comment]
Neither of those statements are in a finally block.

**Comment by iritkatriel** [comment]
Sorry, I was linking to the wrong version of the file. The issue was in v 0.9.0:

https://github.com/tconbeer/sqlfmt/blob/66ea8eb263dd03a1986fbd5a07dbe0e711119fd5/src/sqlfmt/jinjafmt.py#L76
https://github.com/tconbeer/sqlfmt/blob/66ea8eb263dd03a1986fbd5a07dbe0e711119fd5/src/sqlfmt/jinjafmt.py#L78

I suppose this means that the issue has been resolved by now and this can be closed as out of date.
