### ISSUE TITLE
SparkSQL numeric & fractional literals not supported

### ISSUE THREAD

**Issue by ShaneMazur** [tconbeer/sqlfmt#640]
**Describe the bug**
SparkSQL allows for numeric literals as [described here](https://spark.apache.org/docs/latest/sql-ref-literals.html#numeric-literal). sqlfmt breaks sparkSQL code that uses this feature

**To Reproduce**

```sql
-- Unformatted

select -32y as col  -- indicates TINYINT, which is a 1-byte signed integer number
;

```

```sql

-- Formatted
select -32 y as col  -- errors out as the numeric literal must immediately follow the number
;

```

**Expected behavior**

Produce working formatted code with the same behaviour as the unformatted code

**Actual behavior**

Produces unusable sparkSQL code

**Additional context**
What is the output of `sqlfmt --version`?

```
sqlfmt, version 0.23.2
```

What is the output of `pip list` (or `pipx list` if you installed using pipx)?
[pip_list.txt](https://github.com/user-attachments/files/17684546/pip_list.txt)

**Comment by tconbeer** [comment]
Thanks for the issue and the link to the docs!
