### ISSUE TITLE
Using "isnull" function introduces a space between function name and opening parenthesis

### ISSUE THREAD

**Issue by williamscs** [tconbeer/sqlfmt#641]
**Describe the bug**
Using SQL Server's "isnull" function introduces a space between function name and parentheses. This doesn't happen with other functions like "nullif".

**To Reproduce**
I used the main site's "try it out" section to reproduce.

Before fmt
![image](https://github.com/user-attachments/assets/37ff35bd-ec32-44c0-bc7a-b51797ea67a5)

```sql
select isnull(column, 'some string'), nullif(25, 25);
```

After fmt
![image](https://github.com/user-attachments/assets/5f2118af-3bc2-44a6-a0cc-8411588525eb)

```sql
select isnull (column, 'some string'), nullif(25, 25)
;
```

**Expected behavior**
I would expect 'isnull' to be treated the same as 'nullif' where there is no space between the function name and the parenthesis.

**Actual behavior**
A space is introduced.

**Comment by tconbeer** [comment]
That is because, in Postgres and other dialects, `isnull` is an operator that returns a boolean:
![image](https://github.com/user-attachments/assets/013564b3-7c97-4074-a5bb-3644f4733d5d)

We can improve the parser to treat `isnull(` as a function instead.

**Comment by hongtron** [comment]
I'm noticing the same behavior with `filter`, which looks to be a keyword in Postgres, but is a function in SparkSQL:
```
             map_from_entries(
-                filter(
+                filter (
                     transform(
```

Should I open a separate issue for that, or can it be addressed here?

**Comment by tconbeer** [comment]
together is fine. thanks
