### ISSUE TITLE
Formatting error when using the postgres `#>>` operator 

### ISSUE THREAD

**Issue by icornelis-tud** [tconbeer/sqlfmt#654]
**Describe the bug**
postgres sql code using the `#>>`  (Get JSON object at specified path as text) is formatted incorrectly and results in wrong sql code. sqlfmt adds a space between the `#` and `>>`.

**To Reproduce**
format the following example:
```sql
select '{"a":[1,2,3],"b":[4,5,6]}'::json #>>'{a,2}'
```

**Expected behavior**
I expect no formatting changes in this example.

**Actual behavior**
```sql
select '{"a":[1,2,3],"b":[4,5,6]}'::json  # >>'{a,2}'
```
Notice the additional space between  `#` and `>>`.

**Additional context**
What is the output of `sqlfmt --version`?
```
sqlfmt, version 0.24.0

What is the output of `pip list` (or `pipx list` if you installed using pipx)?
```
Package                   Version
------------------------- -----------
agate                     1.9.1
annotated-types           0.7.0
appdirs                   1.4.4
asttokens                 2.4.1
attrs                     24.2.0
babel                     2.16.0
black                     24.10.0
blinker                   1.8.2
certifi                   2024.8.30
chardet                   5.2.0
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
comm                      0.2.2
daff                      1.3.46
dbt-adapters              1.4.1
dbt-common                1.7.0
dbt-core                  1.8.6
dbt-extractor             0.5.1
dbt-postgres              1.8.2
dbt-semantic-interfaces   0.5.1
debugpy                   1.8.6
decorator                 5.1.1
deepdiff                  7.0.1
diff_cover                9.1.1
executing                 2.1.0
Flask                     3.0.3
Flask-Executor            1.0.0
Flask-Shell2HTTP          1.9.1
gunicorn                  23.0.0
idna                      3.8
importlib-metadata        6.11.0
iniconfig                 2.0.0
ipykernel                 6.29.5
ipython                   8.27.0
isodate                   0.6.1
itsdangerous              2.2.0
jedi                      0.19.1
Jinja2                    3.1.4
jinja2-simple-tags        0.6.1
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
jupyter_client            8.6.3
jupyter_core              5.7.2
leather                   0.4.0
Logbook                   1.5.3
MarkupSafe                2.1.5
mashumaro                 3.13.1
matplotlib-inline         0.1.7
minimal-snowplow-tracker  0.0.2
more-itertools            10.4.0
msgpack                   1.0.8
mypy-extensions           1.0.0
nest-asyncio              1.6.0
networkx                  3.3
ordered-set               4.1.0
packaging                 24.1
parsedatetime             2.6
parso                     0.8.4
pathspec                  0.12.1
pexpect                   4.9.0
pip                       24.2
platformdirs              4.3.6
pluggy                    1.5.0
prompt_toolkit            3.0.48
protobuf                  4.25.4
psutil                    6.0.0
psycopg2-binary           2.9.9
ptyprocess                0.7.0
pure_eval                 0.2.3
pydantic                  2.8.2
pydantic_core             2.20.1
Pygments                  2.18.0
pytest                    8.3.2
python-dateutil           2.9.0.post0
python-slugify            8.0.4
pytimeparse               1.1.8
pytz                      2024.1
PyYAML                    6.0.2
pyzmq                     26.2.0
referencing               0.35.1
regex                     2024.7.24
requests                  2.32.3
rpds-py                   0.20.0
setuptools                65.5.0
shandy-sqlfmt             0.24.0
six                       1.16.0
sqlfluff                  3.1.1
sqlfluff-templater-dbt    3.1.1
sqlparse                  0.5.1
stack-data                0.6.3
tblib                     3.0.0
text-unidecode            1.3
tornado                   6.4.1
tqdm                      4.66.5
traitlets                 5.14.3
typing_extensions         4.12.2
urllib3                   2.2.2
wcwidth                   0.2.13
Werkzeug                  3.0.4
zipp                      3.20.1
```

**Comment by tconbeer** [comment]
Duplicates https://github.com/tconbeer/sqlfmt/issues/461
